language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes --option Dpkg::Options::="--force-confnew" docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo cp docker-compose /usr/local/bin && rm docker-compose
install: true

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d
  - docker-compose scale firefox=2 chrome=2
script:
  - >
    mvn clean verify
    -P code-quality,documentation,release
    -DtestProfile=remote
    -Dremote.browser.name=firefox
    -Dremote.firefox.marionette=false
    -DtestPageServerHost=172.17.0.1
  - >
    mvn clean verify
    -P code-quality,documentation,release
    -DtestProfile=remote
    -Dremote.browser.name=chrome
    -DtestPageServerHost=172.17.0.1
after_success:
  - bash <(curl -s https://codecov.io/bash)
