language: java
dist: trusty
install: skip

cache:
  directories:
    - $HOME/.m2/repository

jobs:
  include:

    - stage: compile
      jdk: openjdk8
      env: OpenJDK_8
      script: mvn verify -P ci-compile
    - jdk: oraclejdk8
      env: OracleJDK_8
      script: mvn verify -P ci-compile
    - jdk: openjdk8
      env: TOOL=Checkstyle
      script: mvn verify -P ci-codequality-checkstyle
    - jdk: openjdk8
      env: TOOL=FindBugs
      script: mvn verify -P ci-codequality-findbugs
    - jdk: openjdk8
      env: TOOL=PMD
      script: mvn verify -P ci-codequality-pmd

    - stage: unittests
      jdk: openjdk8
      script: mvn verify -P ci-unittests
      after_success: bash <(curl -s https://codecov.io/bash)
    - jdk: oraclejdk8
      script: mvn verify -P ci-unittests
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: integrationtests
      jdk: openjdk8
      services: docker
      sudo: required
      env: BROWSER=Firefox
      before_script: docker-compose up -d
      script: >
        mvn verify
        -P ci-integrationtests
        -DtestProfile=remote
        -Dremote.browser.name=firefox
        -Dremote.firefox.marionette=false
        -DtestPageServerHost=172.17.0.1
      after_success: bash <(curl -s https://codecov.io/bash)
    - jdk: openjdk8
      services: docker
      sudo: required
      env: BROWSER=Chrome
      before_script: docker-compose up -d
      script: >
        mvn verify
        -P ci-integrationtests
        -DtestProfile=remote
        -Dremote.browser.name=chrome
        -DtestPageServerHost=172.17.0.1
      after_success: bash <(curl -s https://codecov.io/bash)
    - jdk: oraclejdk8
      services: docker
      sudo: required
      env: BROWSER=Firefox
      before_script: docker-compose up -d
      script: >
        mvn verify
        -P ci-integrationtests
        -DtestProfile=remote
        -Dremote.browser.name=firefox
        -Dremote.firefox.marionette=false
        -DtestPageServerHost=172.17.0.1
      after_success: bash <(curl -s https://codecov.io/bash)
    - jdk: oraclejdk8
      services: docker
      sudo: required
      env: BROWSER=Chrome
      before_script: docker-compose up -d
      script: >
        mvn verify
        -P ci-integrationtests
        -DtestProfile=remote
        -Dremote.browser.name=chrome
        -DtestPageServerHost=172.17.0.1
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: documentation
      jdk: openjdk8
      script: mvn verify -P ci-documentation
    - jdk: oraclejdk8
      script: mvn verify -P ci-documentation
